---
title: "EPL_relam"
format: html
---

```{r}
# libraries
library(tidyverse)
library(readxl)
library(nbaR)
library(extrafont) # this has tools for embedding fonts in vector graphics which 
# is required by the design team of the booklet.

loadfonts(device = "pdf") # this is required as device = cairo_pdf is not compatible with CorelDraw

```

```{r}
# import EPL data for each realm and then make integrated table
#COUNTS and EXTENT EPL

epl_count_ter <- read.csv("C:/Rdata/EPL_terr/outputs/results_df_EPL_2024_biome_invasives2.csv")
epl_ext_ter <- read.csv("C:/Rdata/EPL_terr/outputs/results_df_EPL_2024_biome_invasives2_ext.csv")

epl_count_est <- read.csv("C:/Rdata/EPL_est/outputs/epl24_est_sum_count.csv") 
epl_ext_est <- read.csv("C:/Rdata/EPL_est/outputs/epl24_est_sum_ext.csv") 

epl_count_riv <- read.csv("C:/Rdata/EPL_riv/outputs/epl24_riv_sum_count.csv")
epl_ext_riv <- read.csv("C:/Rdata/EPL_riv/outputs/epl24_riv_sum_ext.csv")

epl_count_wet <- read.csv("C:/Rdata/EPL_wet/outputs/epl24_wet_sum_count.csv")
epl_ext_wet <- read.csv("C:/Rdata/EPL_wet/outputs/epl24_wet_sum_ext.csv")

epl_count_mar <- read.csv("C:/Users/skownoa/Dropbox/NBAwork/Marine/EPL_marine_efg_type_table.csv")
epl_ext_mar <- read.csv("C:/Users/skownoa/Dropbox/NBAwork/Marine/EPL_marine_efg_extent_km2_table.csv")


# read in nba2018 results to fill in coastal sub antarctic and marine
nba18eplcount <- read.csv("C:/Users/skownoa/Dropbox/NBAwork/PEI/nba2018_epl_realm_count.csv")
nba18eplext <- read.csv("C:/Users/skownoa/Dropbox/NBAwork/PEI/nba2018_epl_realm_ext.csv")

epl_count_sub <- filter(nba18eplcount, realm == "sub")
epl_count_coa <- filter(nba18eplcount, realm == "coa")
epl_ext_sub <- filter(nba18eplext, realm == "sub")
epl_ext_coa <- filter(nba18eplext, realm == "coa")

```

```{r}
# Clean up and consolidate counts per realm
epl_count_ter <- epl_count_ter %>%
  select(-X, -EPLI) %>%
  rename(zone = T_BIOME) %>%
  mutate(realm = "ter")

epl_count_est <- epl_count_est %>%
  select(-X, -EPLI) %>%
  rename(zone = biogeographical_zone) %>%
  mutate(realm = "est")

epl_count_riv <- epl_count_riv %>%
  select(-X, -EPLI) %>%
  mutate(realm = "riv")

epl_count_wet <- epl_count_wet %>%
  select(-X,-EPLI) %>%
  rename(zone = hgm_simple) %>%
  mutate(realm = "wet")

epl_count_mar <- epl_count_mar %>%
   select(-X) %>%
  rename(zone = ecosystem_functional_type_getl3) %>%
  mutate(realm = "mar") 

# BIND tables of EPL count together
epl_count_zones <- bind_rows(epl_count_ter, epl_count_riv, epl_count_wet, epl_count_mar, epl_count_est)

epl_count_tot <- epl_count_zones %>%
  filter(zone == "Total") %>% 
  relocate(realm, .before = zone) %>% 
  select(-zone) %>%
  bind_rows(
    summarise(., across(WP:Total, \(x) sum(x, na.rm = TRUE))) %>%
      mutate(realm = "Overall")
  ) %>%
  bind_rows(epl_count_coa, epl_count_sub)

epl_count_tot <-  epl_count_tot %>%
  rename( `Well Protected` = WP, 
         `Moderately Protected` = MP, 
         `Poorly Protected` = PP, 
         `Not Protected` = NP ) %>%
   mutate(realm = recode(realm,
                        "sub" = "Sub-Antarctic",
                        "coa" = "Coastal", 
                        "mar" = "Marine",
                        "est" = "Estuarine",
                        "wet" = "Wetland",
                        "riv" = "River",
                        "ter" = "Terrestrial",
                        "Overall" = "Overall"))  %>%  
mutate(realm = factor(realm, levels = c("Overall", "Sub-Antarctic", "Coastal", "Estuarine", "Marine",  "Wetland", "River", "Terrestrial"))) %>%
  arrange(realm) %>%
  filter(realm != "Overall")


# Write to file
write.csv(epl_count_tot, "outputs/epl_count_per_realm.csv")
```

```{r}
# Clean upand consolidate extent per realm
epl_ext_ter <- epl_ext_ter %>%
  select(-X) %>%
  rename(zone = T_BIOME) %>%
  mutate(realm = "ter")

epl_ext_est <- epl_ext_est %>%
  select(-X) %>%
  rename(zone = biogeographical_zone) %>%
  mutate(realm = "est")

epl_ext_riv <- epl_ext_riv %>%
  select(-X) %>%
  mutate(realm = "riv")

epl_ext_wet <- epl_ext_wet %>%
  select(-X) %>%
  rename(zone = hgm_simple) %>%
  mutate(realm = "wet")

epl_ext_mar <- epl_ext_mar %>%
  select(-X) %>%
  rename(zone = ecosystem_functional_type_getl3) %>%
  mutate(realm = "mar") 

# BIND tables of EPL count together
epl_ext_zones <- bind_rows(epl_ext_ter, epl_ext_riv, epl_ext_wet, epl_ext_est, epl_ext_mar)

epl_ext_tot <- epl_ext_zones %>%
  filter(zone == "Total") %>% 
  relocate(realm, .before = zone) %>% 
  select(-zone) %>%
  bind_rows(
    summarise(., across(WP:Total, \(x) sum(x, na.rm = TRUE))) %>%
      mutate(realm = "Overall")
  ) %>%
  bind_rows(epl_ext_coa,epl_ext_sub )

epl_ext_tot <-  epl_ext_tot %>%
   rename( `Well Protected` = WP, 
         `Moderately Protected` = MP, 
         `Poorly Protected` = PP, 
         `Not Protected` = NP ) %>%
   mutate(realm = recode(realm,
                        "sub" = "Sub-Antarctic",
                        "coa" = "Coastal", 
                        "mar" = "Marine",
                        "est" = "Estuarine",
                        "wet" = "Wetland",
                        "riv" = "River",
                        "ter" = "Terrestrial",
                        "Overall" = "Overall"))  %>%  
mutate(realm = factor(realm, levels = c("Overall", "Sub-Antarctic", "Coastal", "Estuarine", "Marine",  "Wetland", "River", "Terrestrial"))) %>%
  arrange(realm) %>%
  filter(realm != "Overall")

# Write to file
write.csv(epl_ext_tot, "outputs/epl_ext_per_realm.csv")
```

```{r}
# Make COUNT plots for booklet

epl_count_plot <- nba_plot(epl_count_tot,
                     `realm`,
                     2:5,
                     CHRT = "bar",
                     NUM = TRUE,
                     LAB = "Percentage of ecosystem types",
                     SAVE = NULL,
                     SCALE_TEXT = 0.6)

epl_count_plot <- epl_count_plot +
  theme(
    legend.position = "bottom",             # keep it at the bottom
    legend.margin = margin(l = -45, r = -5, t = -5, b = -5))

ggsave(
  filename = "outputs/epl_count_plot.pdf",    # File name with extension for format
  plot = epl_count_plot,
  device = "pdf", # this embeds the fonts for GE to use (see first step of addfont)
  width = 9, height = 7, units = "cm") 


# png format for maps and web content plots and maps 
ggsave(
  filename = "outputs/epl_count_plot.png",    # File name with extension for format
  plot = epl_count_plot,
  dpi = 300, 
  width = 9, height = 7, units = "cm") 

```

```{r}
# Make EXT plots for booklet

epl_ext_plot <- nba_plot(epl_ext_tot,
                     `realm`,
                     2:5,
                     CHRT = "bar",
                     NUM = FALSE,
                     LAB = "Percentage of ecosystem extent",
                     SAVE = NULL,
                     SCALE_TEXT = 0.6)

epl_ext_plot <- epl_ext_plot +
  theme(
    legend.position = "bottom",             # keep it at the bottom
    legend.margin = margin(l = -45, r = -5, t = -5, b = -5))

ggsave(
  filename = "outputs/epl_ext_plot.pdf",    # File name with extension for format
  plot = epl_ext_plot,
  device = "pdf", # this embeds the fonts for GE to use (see first step of addfont)
  width = 9, height = 7, units = "cm") 


# png format for maps and web content plots and maps 
ggsave(
  filename = "outputs/epl_ext_plot.png",    # File name with extension for format
  plot = epl_ext_plot,
  dpi = 300, 
  width = 9, height = 7, units = "cm") 

```
