---
title: "RLE_realm"
format: html
---

```{r}
# libraries
library(tidyverse)
library(readxl)
library(nbaR)
library(extrafont) # this has tools for embedding fonts in vector graphics which 
# is required by the design team of the booklet.

loadfonts(device = "pdf") # this is required as device = cairo_pdf is not compatible with CorelDraw

```

```{r}
# import RLE data for each realm and then make integrated table
#COUNTS and EXTENT RLE

ter_results <- read.csv("C:/Rdata/RLE_terr/outputs/ter_results_for_integration.csv")

riv_results <- read.csv("C:/Rdata/RLE_riv/outputs/riv_results_for_integration.csv")

#wet_results <- read.csv("C:/Rdata/RLE_wet/outputs/wet_results_for_integration.csv")

est_results <- read.csv("C:/Rdata/RLE_est/outputs/est_results_for_integration.csv")

mar_results <- read.csv("C:/Users/skownoa/Dropbox/NBAwork/Marine/mar_results_for_integration.csv")


# read in nba2018 results to fill in  sub antarctic / marine
nba18rlecount <- read.csv("C:/Users/skownoa/Dropbox/NBAwork/PEI/nba2018_rle_realm_count.csv")
nba18rleext <- read.csv("C:/Users/skownoa/Dropbox/NBAwork/PEI/nba2018_rle_realm_ext.csv")
nba18eplcount <- read.csv("C:/Users/skownoa/Dropbox/NBAwork/PEI/nba2018_epl_realm_count.csv")
nba18eplext <- read.csv("C:/Users/skownoa/Dropbox/NBAwork/PEI/nba2018_epl_realm_ext.csv")

sub_rle_count <- filter(nba18rlecount, realm == "sub") %>% select(-Total)
sub_rle_ext   <- filter(nba18rleext, realm == "sub") %>% select(-Total)
sub_epl_count <- filter(nba18eplcount, realm == "sub") %>% select(-Total)
sub_epl_ext   <- filter(nba18eplext, realm == "sub") %>% select(-Total)

# use nba2018 results for wetlands and coastal for now
coa_rle_count <- filter(nba18rlecount, realm == "coa") %>% select(-Total)
coa_rle_ext   <- filter(nba18rleext, realm == "coa") %>% select(-Total)
coa_epl_count <- filter(nba18eplcount, realm == "coa") %>% select(-Total)
coa_epl_ext   <- filter(nba18eplext, realm == "coa") %>% select(-Total)

wet_rle_count <- filter(nba18rlecount, realm == "wet") %>% select(-Total)
wet_rle_ext   <- filter(nba18rleext, realm == "wet") %>% select(-Total)
wet_epl_count <- filter(nba18eplcount, realm == "wet") %>% select(-Total)
wet_epl_ext   <- filter(nba18eplext, realm == "wet") %>% select(-Total)
```

```{r}
ter_rle_count <- ter_results %>%
  select(RLE, type) %>%
    count(RLE) %>%
  pivot_wider(names_from = RLE, values_from = n, values_fill = 0) %>%
  mutate(realm = "ter")
ter_rle_extent <- ter_results %>%
  select(RLE, extent) %>%
  group_by(RLE) %>%
  summarise(tot_extent = sum(extent, na.rm = TRUE)) %>%
  pivot_wider(names_from = RLE, values_from = tot_extent, values_fill = 0) %>%
  mutate(realm = "ter")
  
mar_rle_count <- mar_results %>%
  select(RLE, type) %>%
    count(RLE) %>%
  pivot_wider(names_from = RLE, values_from = n, values_fill = 0) %>%
  mutate(realm = "mar") %>%
  mutate(LC = NT + LC) %>% select(-NT)
mar_rle_extent <- mar_results %>%
  select(RLE, extent) %>%
  group_by(RLE) %>%
  summarise(tot_extent = sum(extent, na.rm = TRUE)) %>%
  pivot_wider(names_from = RLE, values_from = tot_extent, values_fill = 0) %>%
  mutate(realm = "mar") %>%
  mutate(LC = NT + LC) %>% select(-NT)

est_rle_count <- est_results %>%
  select(RLE, type) %>%
    count(RLE) %>%
  pivot_wider(names_from = RLE, values_from = n, values_fill = 0) %>%
  mutate(realm = "est")
est_rle_extent <- est_results %>%
  select(RLE, extent) %>%
  group_by(RLE) %>%
  summarise(tot_extent = sum(extent, na.rm = TRUE)) %>%
  pivot_wider(names_from = RLE, values_from = tot_extent, values_fill = 0) %>%
  mutate(realm = "est")

riv_rle_count <- riv_results %>%
  select(RLE, type) %>%
    count(RLE) %>%
  pivot_wider(names_from = RLE, values_from = n, values_fill = 0) %>%
  mutate(realm = "riv")
riv_rle_extent <- riv_results %>%
  select(RLE, extent) %>%
  group_by(RLE) %>%
  summarise(tot_extent = sum(extent, na.rm = TRUE)/1e6) %>%
  pivot_wider(names_from = RLE, values_from = tot_extent, values_fill = 0) %>%
  mutate(realm = "riv")

# wet_rle_count <- wet_results %>%
#   select(RLE, type) %>%
#     count(RLE) %>%
#   pivot_wider(names_from = RLE, values_from = n, values_fill = 0) %>%
#   mutate(realm = "wet")
# wet_rle_extent <- wet_results %>%
#   select(RLE, extent) %>%
#   group_by(RLE) %>%
#   summarise(tot_extent = sum(extent, na.rm = TRUE)) %>%
#   pivot_wider(names_from = RLE, values_from = tot_extent, values_fill = 0) %>%
#   mutate(realm = "wet")

# Add coastal when done
  
```

```{r}
ter_epl_count <- ter_results %>%
  select(EPL, type) %>%
    count(EPL) %>%
  pivot_wider(names_from = EPL, values_from = n, values_fill = 0) %>%
  mutate(realm = "ter")
ter_epl_extent <- ter_results %>%
  select(EPL, extent) %>%
  group_by(EPL) %>%
  summarise(tot_extent = sum(extent, na.rm = TRUE)) %>%
  pivot_wider(names_from = EPL, values_from = tot_extent, values_fill = 0) %>%
  mutate(realm = "ter")
  
mar_epl_count <- mar_results %>%
  select(EPL, type) %>%
    count(EPL) %>%
  pivot_wider(names_from = EPL, values_from = n, values_fill = 0) %>%
  mutate(realm = "mar")
mar_epl_extent <- mar_results %>%
  select(EPL, extent) %>%
  group_by(EPL) %>%
  summarise(tot_extent = sum(extent, na.rm = TRUE)) %>%
  pivot_wider(names_from = EPL, values_from = tot_extent, values_fill = 0) %>%
  mutate(realm = "mar")
  
est_epl_count <- est_results %>%
  select(EPL, type) %>%
    count(EPL) %>%
  pivot_wider(names_from = EPL, values_from = n, values_fill = 0) %>%
  mutate(realm = "est")
est_epl_extent <- est_results %>%
  select(EPL, extent) %>%
  group_by(EPL) %>%
  summarise(tot_extent = sum(extent, na.rm = TRUE)) %>%
  pivot_wider(names_from = EPL, values_from = tot_extent, values_fill = 0) %>%
  mutate(realm = "est")

riv_epl_count <- riv_results %>%
  select(EPL, type) %>%
    count(EPL) %>%
  pivot_wider(names_from = EPL, values_from = n, values_fill = 0) %>%
  mutate(realm = "riv")
riv_epl_extent <- riv_results %>%
  select(EPL, extent) %>%
  group_by(EPL) %>%
  summarise(tot_extent = sum(extent, na.rm = TRUE)/1e6) %>%
  pivot_wider(names_from = EPL, values_from = tot_extent, values_fill = 0) %>%
  mutate(realm = "riv")
```

```{r}

# BIND tables of RLE count together
rle_count_all <- bind_rows(ter_rle_count, mar_rle_count, riv_rle_count, wet_rle_count, est_rle_count, coa_rle_count, sub_rle_count) %>%
  rename( `Critically Endangered` = CR, 
         `Endangered` = EN, 
         `Vulnerable` = VU, 
         `Least Concern` = LC ) %>%
   mutate(realm = recode(realm,
                        "sub" = "Sub-Antarctic",
                        "coa" = "Coastal", 
                        "mar" = "Marine",
                        "est" = "Estuarine",
                        "wet" = "Wetland",
                        "riv" = "River",
                        "ter" = "Terrestrial"))  %>%  
mutate(realm = factor(realm, levels = c("Sub-Antarctic", "Coastal", "Estuarine", "Marine",  "Wetland", "River", "Terrestrial"))) %>%
  arrange(realm)

# Write to file
write.csv(rle_count_all, "outputs/rle_count_per_realm.csv")

# BIND tables of RLE extent together
rle_ext_all <- bind_rows(ter_rle_ext, mar_rle_ext, riv_rle_ext, wet_rle_ext, est_rle_ext, coa_rle_ext, sub_rle_ext) %>%
  rename( `Critically Endangered` = CR, 
         `Endangered` = EN, 
         `Vulnerable` = VU, 
         `Least Concern` = LC ) %>%
   mutate(realm = recode(realm,
                        "sub" = "Sub-Antarctic",
                        "coa" = "Coastal", 
                        "mar" = "Marine",
                        "est" = "Estuarine",
                        "wet" = "Wetland",
                        "riv" = "River",
                        "ter" = "Terrestrial"))  %>%  
mutate(realm = factor(realm, levels = c("Sub-Antarctic", "Coastal", "Estuarine", "Marine",  "Wetland", "River", "Terrestrial"))) %>%
  arrange(realm)

# Write to file
write.csv(rle_ext_all, "outputs/rle_ext_per_realm.csv")
```

```{r}
# Clean upand consolidate extent per realm
epl_ext_ter <- epl_ext_ter %>%
  select(-X) %>%
  rename(zone = T_BIOME) %>%
  mutate(realm = "ter")

epl_ext_est <- epl_ext_est %>%
  select(-X) %>%
  rename(zone = biogeographical_zone) %>%
  mutate(realm = "est")

epl_ext_riv <- epl_ext_riv %>%
  select(-X) %>%
  mutate(realm = "riv")

epl_ext_wet <- epl_ext_wet %>%
  rename(zone = hgm) %>%
  mutate(realm = "wet")

rle_ext_mar <- rle_ext_mar %>%
  mutate(LC = LC+NT) %>%
  select(-X, -NT) %>%
  rename(zone = ecosystem_functional_type_getl3) %>%
  mutate(realm = "mar") 

# BIND tables of RLE count together
rle_ext_zones <- bind_rows(rle_ext_ter, rle_ext_riv, rle_ext_wet, rle_ext_est, rle_ext_mar, rle_ext_coa)

rle_ext_tot <- rle_ext_zones %>%
  filter(zone == "Total") %>% 
  relocate(realm, .before = zone) %>% 
  select(-zone) %>%
  bind_rows(
    summarise(., across(CR:Total, \(x) sum(x, na.rm = TRUE))) %>%
      mutate(realm = "Overall")
  ) %>%
  bind_rows(rle_ext_sub )

rle_ext_tot <-  rle_ext_tot %>%
  rename( `Critically Endangered` = CR, 
         `Endangered` = EN, 
         `Vulnerable` = VU, 
         `Least Concern` = LC ) %>%
   mutate(realm = recode(realm,
                        "sub" = "Sub-Antarctic",
                        "coa" = "Coastal", 
                        "mar" = "Marine",
                        "est" = "Estuarine",
                        "wet" = "Wetland",
                        "riv" = "River",
                        "ter" = "Terrestrial",
                        "Overall" = "Overall"))  %>%  
mutate(realm = factor(realm, levels = c("Overall", "Sub-Antarctic", "Coastal", "Estuarine", "Marine",  "Wetland", "River", "Terrestrial"))) %>%
  arrange(realm) %>%
  filter(realm != "Overall")

# Write to file
write.csv(rle_ext_tot, "outputs/rle_ext_per_realm.csv")
```

```{r}
# Make COUNT plots for booklet

rle_count_plot <- nba_plot(rle_count_tot,
                     `realm`,
                     2:5,
                     CHRT = "bar",
                     NUM = TRUE,
                     LAB = "Percentage of ecosystem types",
                     SAVE = NULL,
                     SCALE_TEXT = 0.6)

rle_count_plot <- rle_count_plot +
  theme(
    legend.position = "bottom",             # keep it at the bottom
    legend.margin = margin(l = -45, r = -5, t = -5, b = -5))

ggsave(
  filename = "outputs/rle_count_plot.pdf",    # File name with extension for format
  plot = rle_count_plot,
  device = "pdf", # this embeds the fonts for GE to use (see first step of addfont)
  width = 9, height = 7, units = "cm") 


# png format for maps and web content plots and maps 
ggsave(
  filename = "outputs/rle_count_plot.png",    # File name with extension for format
  plot = rle_count_plot,
  dpi = 300, 
  width = 9, height = 7, units = "cm") 

```

```{r}
# Make EXT plots for booklet

rle_ext_plot <- nba_plot(rle_ext_tot,
                     `realm`,
                     2:5,
                     CHRT = "bar",
                     NUM = FALSE,
                     LAB = "Percentage of ecosystem extent",
                     SAVE = NULL,
                     SCALE_TEXT = 0.6)

rle_ext_plot <- rle_ext_plot +
  theme(
    legend.position = "bottom",             # keep it at the bottom
    legend.margin = margin(l = -45, r = -5, t = -5, b = -5))

ggsave(
  filename = "outputs/rle_ext_plot.pdf",    # File name with extension for format
  plot = rle_ext_plot,
  device = "pdf", # this embeds the fonts for GE to use (see first step of addfont)
  width = 9, height = 7, units = "cm") 


# png format for maps and web content plots and maps 
ggsave(
  filename = "outputs/rle_ext_plot.png",    # File name with extension for format
  plot = rle_ext_plot,
  dpi = 300, 
  width = 9, height = 7, units = "cm") 

```

```{r}

```
